### ISSUE TITLE
second RM Mini3

### ISSUE THREAD

**Issue by suibaf** [TheGU/rm3_mini_controller#2]
Hi,
It work fine with RM Mini 3.
Is there a chance to drive a second RM Mini?
Best Regards

**Comment by TheGU** [comment]
You can control many RM3 but not in the same time. You need to each of them separately.
First add second RM3's detail to BlackBeanControl.ini with new name
[ SecondRM3Name]
IPAddress = 
Port = 80
MACAddress = 
Timeout = 3

Next you can call it with -d argument to specific each RM3
e.g.
python BlackBeanControl.py -c COMMAND1 -d FirstRM3Name
python BlackBeanControl.py -c COMMAND1 -d SecondRM3Name
